end_time = ""
is_start_session = ""
price_per_minute = ""
session_commitment = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
session_id = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
slot_id = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
start_time = ""
total_reward = ""
